name: Secret Test

on: workflow_dispatch

jobs:
  secret_job:
    runs-on: ubuntu-latest

    steps:
      - name: Test secret
        run: echo "Mon secret existe"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

      - name: Check secret
        run: |
          if [ -n "$MY_SECRET" ]; then
            echo "Le secret est bien récupéré"
          else
            echo "Le secret est vide"
            exit 1
          fi
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
